export const TOKEN_CHANGE = "token_change"
export const USER_INFO = "user_info"
export const USER_ORGID = "user_orgid"
export const SELECT_ORGID = "select_user_orgid"
export const SELECT_ORGNAME = "select_user_orgname"
export const MENULIST = "menu_list"
